<a href="https://colab.research.google.com/github/darimul/ulrich/blob/main/Numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a) Импортируйте библиотеку NumPy

In [1]:
import numpy as np

b) Создайте массив из 10 нулей

In [2]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


c) Создать массив из 10 единиц

In [3]:
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


d) Создать массив из 10 пятерок

In [4]:
c = b*5
print(c)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


e) Создать массив из целых чисел от 10 до 50

In [5]:
d = np.arange(10, 51)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


f) Создать массив из четных чисел от 10 до 50

In [6]:
f = np.arange(10, 51, 2)
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


g) Создать матрицу 3х3 с числами от 0 до 8

In [7]:
 g = np.arange(9).reshape(3,3)
 print(g)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


h) Создать единичную матрицу 3x3

In [8]:
h = np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


i) Используйте NumPy для генерации случайного числа от 0 до 1

In [10]:
i = np.random.rand(1)
print(i)


[0.97852225]


j) Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

In [11]:
j = np.random.rand(25)
print(j)

[0.34260642 0.22191554 0.53653617 0.12620672 0.41222357 0.88256315
 0.34016309 0.81560512 0.76337825 0.92598808 0.98526217 0.2031948
 0.21102725 0.96240243 0.69897744 0.31502092 0.28535705 0.34994496
 0.81763992 0.64491549 0.90519012 0.02404094 0.64392316 0.4641181
 0.0336902 ]


k) Создайте следующую матрицу используя функции библиотеки NumPy:

In [13]:
k = np.arange(0, 1.01, 0.01)
print(k)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


l) Дана стартовая матрица (обязательно запустите код ниже в вашемрешении!). Эта матрица будет использоваться в последующих задачах

In [14]:
mat = np.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Необходимо написать код который вернет следующую матрицуиз стартовой:

In [15]:
print('l =', mat[2:, 1:])

l = [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


m) Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l.

In [20]:

m = mat[mat == 20]
print(m)

[20]


n) Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [17]:
print('n =', mat[0:3, 1].reshape(3,1))

n = [[ 2]
 [ 7]
 [12]]


o) Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [18]:
print('o =', mat[4:])

o = [[21 22 23 24 25]]


p) Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [22]:
print('p =', mat[3:])

p = [[16 17 18 19 20]
 [21 22 23 24 25]]


q) Получить сумму всех значений в стартовой матрице mat

In [24]:
print(mat.sum())

325


r) Получить стандартное отклонение в стартовой матрице mat

In [25]:
print(mat.std())

7.211102550927978


s) Получить сумму значений в колонках в стартовой матрице mat

In [26]:
print(mat.sum(axis=0))

[55 60 65 70 75]
